### ISSUE TITLE
lmysqlclient

### ISSUE THREAD

**Issue by susl16c** [OlafvdSpek/xbt#109]
/usr/bin/ld:cannot find -lmysqlclient
/usr/bin/ld: cannot find -systems
collect2: error: ld execution ended with return code 1
make[2]: *** [CMakeFiles/xbt_tracker.dir/build.make:273: xbt_tracker] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/xbt_tracker.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by yetdog** [comment]
find / -name libmysqlclient.so
ln -s /usr/lib64/mysql/libmysqlclient.so /usr/lib64/libmysqlclient.so
