### ISSUE TITLE
error with ssl

### ISSUE THREAD

**Issue by Q8hma** [OlafvdSpek/xbt#48]
Hello

I have little problem with https
i have https work fine but with xbt i got this msg
`Tracker Status:	Tracker: [SSL connect error]`

what is the problem ?? and how can i fix it

thnx

**Comment by OlafvdSpek** [comment]
XBT Tracker does not support SSL directly, you have to proxy it (via nginx).

**Comment by Q8hma** [comment]
Hello 

I used cpanel how can I do it ??

Thnx

**Comment by OlafvdSpek** [comment]
I don't know, ask cpanel.

**Comment by Q8hma** [comment]
Thnx for Ur help :)

**Comment by OlafvdSpek** [comment]
You're welcome
