### ISSUE TITLE
torrent hash

### ISSUE THREAD

**Issue by Q8hma** [OlafvdSpek/xbt#49]
Hello
can u make some change to make it support hex info_hash or torrent id ?

thnx

**Comment by OlafvdSpek** [comment]
What's wrong with binary info_hash?
And what's torrent id?

**Comment by Q8hma** [comment]
Hello
I have little problem with it because i have 20k torrents with hex and i cant make new with binary
and torrent it is AUTO_INCREMENT i add it to announce url to find it fast

**Comment by Q8hma** [comment]
when i do 
UNHEX(info_hash) or concat('0x',info_hash)
it give my 42 character not 20

**Comment by Q8hma** [comment]
and can u plz support https

**Comment by Q8hma** [comment]
Hello bro
Any update?
Thnx

**Comment by OlafvdSpek** [comment]
Https is best supported by putting nginx in front of the tracker to deal with the SSL stuff.

I'm not sure what's going on with your info-hashes..

**Comment by Q8hma** [comment]
thnx bro for the help

i will try to see what is the problem
