### ISSUE TITLE
Activate Freeleech

### ISSUE THREAD

**Issue by pokapow** [OlafvdSpek/xbt#50]
I don't find the gold option for activate freeleech on xbt. Is that in database ?
Do there is another way to activate freeleech for everyone for few days in a private tracker ?

**Comment by OlafvdSpek** [comment]
Hi pokapow,

Freeleech is a paid add-on, contact me @ olafvdspek@gmail.com if interested.

**Comment by Q8hma** [comment]
@OlafvdSpek is it only one plug-in or full staff ??

thanks

**Comment by OlafvdSpek** [comment]
What does "full staff" mean?
It's an update of the tracker source files.

**Comment by Q8hma** [comment]
yep i know its update the source code
but the freeleech is plugin like
- free torrent - limit time or unlimit
- x2/x4 torrent - limit time or unlimit
- gold user (vip/donation) - limit time or unlimit

like that

**Comment by OlafvdSpek** [comment]
It allows you to set per-torrent and per-user multipliers (0, 0.5, 1, 2, whatever you want). You control them yourself, if you want a limited time you'll have to reset them yourself.

**Comment by Q8hma** [comment]
if i want them how much it will cost ??

thnx

**Comment by Q8hma** [comment]
and if i want to add info_hash (hex) or torrent id

**Comment by pokapow** [comment]
Hello Olaf,
I email you again about freeleech, your patch is not working.
