### ISSUE TITLE
Problem with 'on duplicate key update' with colums default set to NULL 

### ISSUE THREAD

**Issue by Squeeze2007** [OlafvdSpek/xbt#53]
Hello,
I get error <ERROR 1364 (HY000): Field 'name' doesn't have a default value> with query 
<insert into torrents (leechers, seeders, completed, id) values (0,1,0,1) on duplicate key update  leechers = values(leechers),  seeders = values(seeders),  completed = values(completed),  mtime = unix_timestamp()>

I dont get this error with query < insert into torrents (leechers, seeders, completed, id, name) values (0,1,0,1, name) on duplicate key update  leechers = values(leechers),  seeders = values(seeders),  completed = values(completed),  mtime = unix_timestamp()>

Here my 'name' column informations :
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| name        | varchar(255) | NO   |     | NULL    |                |

Did you have a tips to resolve this problem ?

**Comment by OlafvdSpek** [comment]
You could set defaults for all fields. 
You could try `insert ignore into`.
You could use MyISAM instead of InnoDB.
You could buy MySQL and MariaDB to support batch-update queries.
