### ISSUE TITLE
make.sh file doesn't seem to be needed anymore in Tracker

### ISSUE THREAD

**Issue by kerokim** [OlafvdSpek/xbt#57]
Recent code changes, server.cpp file was renamed tracker.cpp in the Tracker directory.
However, the make.sh file does not seem to reflect this change.

By the way, without using the 'make.sh' script file, the 'cmake' and 'make' command alone seems to have no problem with build.
So I think it would be better to remove the make.sh file from the Tracker directory.

Thank you for your hard work.

**Comment by OlafvdSpek** [comment]
Thanks. You're right, it's not really necessary. One difference is `make.sh` uses `mysql_config --libs` where cmake doesn't. I'm keeping it for now if you don't mind.
