### ISSUE TITLE
MySql 5.7 Issue

### ISSUE THREAD

**Issue by XFDev-v2** [OlafvdSpek/xbt#61]
Xbt not working properly with MySQL 5.7, peers table is getting updated, however users table and files table is not getting updated on MySQL 5.7 , degraded to 5.6 and everything works fine.

Looks like some changes in 5.7 are affecting it. This is what i found regarding it :- 

Some changes have been introduced in the default SQL mode - right now MySQL uses STRICT_TRANS_TABLES by default. This is great change but it sure can break compatibility with older applications.

I hope it gets fixed.

**Comment by OlafvdSpek** [comment]
You can disable STRICT_TRANS_TABLES or set defaults for all fields in files and users tables.
