### ISSUE TITLE
Pass doesn't work

### ISSUE THREAD

**Issue by AngelOfFear** [OlafvdSpek/xbt#79]
Sorry in my english (i'm from Russia).
- I imported xbt_tracker.sql and added info_hashes to xbt_torrents (auto_register = 0).
- Inserted user with uid = 1 to xbt_users (by the way why the uid is a autoincrement? The xbt_users must be filled in by the XBTT automatically or I must insert all my registered users?).
- Generating a password
```
SELECT HEX(info_hash) AS hex_ih FROM content_table WHERE ...
...
SELECT torrent_pass_version,value FROM xbt_users, xbt_config WHERE uid=1 AND name='torrent_pass_private_key'
...
$passkey = sprintf('%08x%s', $_SESSION['uid'], substr(sha1(sprintf('%s %d %d %s', $row2['value'], $row2['torrent_pass_version'], $_SESSION['uid'], pack('H*', $row['hex_ih']))), 0, 24));
----------
$_SESSION['uid'] equals 1
$row2['value'] equals uBm6upQ2RziQL6QkYUcTp3XNbpL (created automatically when XBTT starting)
$row2['torrent_pass_version'] equals 0
$row['hex_ih'] equals 7a0fac1e0994b78f5c74625f93fd43cfb45dc589
announce_url equals udp://mydomain:2710/00000001a0a682b1095e566ed613690f/announce
```
If I set anonymous_announce and anonymous_scrape to 0 (by default), I see "access denied" in the uTorrent.
If I set anonymous_announce and anonymous_scrape to 1, I see 1 leechers in the uTorrent and xbt_torrents. But xbt_peers is empty. And in xbt_user downloaded/uploaded stays at 0.
If I created table xbt_announce_log (by the way in xbt_tracker.sql have **ipv6** column, but in the source is a **ipa**) and set log_announce to 1, I see peer in xbt_announce_log where uid is 0.
It seems to me pass doesn't work. Fix pleas.

**Comment by OlafvdSpek** [comment]
> HEX(info_hash)

I don't think it should be hexed..
It's simplest to create the torrent_pass column and to generate 32-char passes, then you can skip the sha1 tricks.

>  or I must insert all my registered users?).

That's your job, XBT wouldn't known your users otherwise.

**Comment by AngelOfFear** [comment]
info_hash in my content_table has a binary(20) type, so I select HEX(info_hash). Because [this page](https://visigod.com/xbt-tracker/general-tips) shows that it should be hex(40). And because it using in function pack('H*', ...), where H means hex.
If I select binary info_hash, then pass equals 000000017dcf5533ae8e1a4433dada8b, and it still doesn't work.
If I select binary info_hash and use instead of a function pack(), then pass equals 00000001a0a682b1095e566ed613690f as in the my first post.
If I add torrent_pass char(32) column and paste 00000001a0a682b1095e566ed613690f and use udp://mydomain:2710/00000001a0a682b1095e566ed613690f/announce it still doesn't work. xbt_peers is still empty and xbt_user downloaded/uploaded stays at 0.

**Comment by OlafvdSpek** [comment]
UDP doesn't support authentication, try http

**Comment by AngelOfFear** [comment]
Thanks! Over http works! You need to specify this information somewhere.
