### ISSUE TITLE
Errors with using from Docker

### ISSUE THREAD

**Issue by Asethon** [OlafvdSpek/xbt#81]
Hey. I tried to use this service to work inside the docker.
To do this, I created a dockerfile based on the image of mariadb:

```
FROM mariadb:10.3

RUN apt-get update && apt-get install -y cmake default-libmysqlclient-dev g++ git libboost-dev make zlib1g-dev
RUN git clone https://github.com/OlafvdSpek/xbt

RUN cd xbt/Tracker && \
        cmake . && \
        make
COPY xbt_tracker/xbt_tracker.conf /xbt/bin/

RUN cd xbt/Tracker && adduser --disabled-login xbt && \
        cp xbt_tracker /xbt/bin && \
        chmod 700 /xbt/bin/xbt_tracker.conf && \
        chown -R xbt:xbt /xbt/bin
COPY xbt_tracker/xbt.bash /root/

RUN chmod 755 /root/xbt.bash
COPY xbt_tracker/rc.local /etc/
```

```
# /xbt/bin/xbt_tracker.conf
mysql_host = mariadb
mysql_user = anilibria
mysql_password = anilibria
mysql_database = anilibria
```

```
# /root/xbt.bash
#!/bin/bash -x
sleep 60
su - xbt -c "cd /home/xbt/bin && ./xbt_tracker > /dev/null 2>/dev/null &"
```
Next, I run the command `/root/xbt.bash &` inside the container

I have empty tables xbt_peers and xbt_torrents.
Service crashes with the following error:

![image](https://user-images.githubusercontent.com/34743506/78322123-7489cc80-7576-11ea-809d-73a8f44f7260.png)

Also, on port 2710 that I specified, the browser crashes with the error ERR_CONNECTION_CLOSED

Could you tell me how to fix the problems?

**Comment by iseeyoucopy** [comment]
try 
 killall  ./xbt_tracker

bind faiure: EADDRINUSE - That's mean you already started xbt_tracker
