### ISSUE TITLE
sql_mode = STRICT_TRANS_TABLES

### ISSUE THREAD

**Issue by AngelOfFear** [OlafvdSpek/xbt#82]
If sql_mode = STRICT_TRANS_TABLES, seeders and leechers in xbt_torrents are 0.

**Comment by OlafvdSpek** [comment]
So don't set STRICT_TRANS_TABLES ;)

**Comment by AngelOfFear** [comment]
I have Ubuntu 20.04 and Mariadb 10.3.22 and **default** sql_mode = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by OlafvdSpek** [comment]
You're not locked to the default.

**Comment by AngelOfFear** [comment]
Yes, I disabled it, but it's not good. Can you fix it or at least specify it in the readme? It took me a long time to find out why.

**Comment by OlafvdSpek** [comment]
Fixed
