### ISSUE TITLE
Request: Add keep alive feature

### ISSUE THREAD

**Issue by an0n666** [OlafvdSpek/xbt#83]
Xbt force connections to be closed after each request for obvious reasons. However, reverse-proxying is a pretty common thing, so keep-alive feature should be added and maybe make it configurable.
As it makes no sense to keep creating new TCP connections when you could be re-utilising the same connection with the proxy.

Currently I'm doing reverse-proxy using Nginx for HTTPS and it would really help if those additional roundtrips could be avoided by using keep-alive.

Please close this if you don't take any feature requests here.

**Comment by OlafvdSpek** [comment]
> Currently I'm doing reverse-proxy using Nginx for HTTPS and it would really help if those additional roundtrips could be avoided by using keep-alive.

Is that based on measurements? ;)

Are you proxying from localhost?

**Comment by an0n666** [comment]
No I’m proxying from both localhost and from another server located overseas which has better latency to users. The localhost one works fine but overseas proxy creates new connections for every request.

**Comment by OlafvdSpek** [comment]
You could have nginx take care of the keep-alive connections.

**Comment by an0n666** [comment]
Or use another tracker which has better support for proxies. Anyways thanks.
