### ISSUE TITLE
Build fails with SOCK_NONBLOCK

### ISSUE THREAD

**Issue by an0n666** [OlafvdSpek/xbt#84]
Build fails when built with SOCK_NONBLOCK. Otherwise builds fine.
Ubuntu 18.04.3 LTS.

[  8%] Building CXX object CMakeFiles/xbt_tracker.dir/home/user/Desktop/xbt-master/misc/bt_misc.cpp.o
<command-line>:0:15: error: expected identifier before numeric constant
<command-line>:0:15: error: expected ‘}’ before numeric constant
<command-line>:0:15: error: expected unqualified-id before numeric constant
In file included from /usr/include/features.h:424:0,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/7/bits/c++config.h:533,
                 from /usr/include/c++/7/cstddef:49,
                 from /usr/include/boost/config/compiler/gcc.hpp:165,
                 from /usr/include/boost/config.hpp:39,
                 from /usr/include/boost/range/iterator_range_core.hpp:17,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /home/user/Desktop/xbt-master/Tracker/../misc/xbt/data_ref.h:3,
                 from /home/user/Desktop/xbt-master/misc/xbt/bt_misc.h:3,
                 from /home/user/Desktop/xbt-master/misc/bt_misc.cpp:1:
/usr/include/x86_64-linux-gnu/sys/socket.h:272:1: error: expected declaration before ‘}’ token
 __END_DECLS
 ^
CMakeFiles/xbt_tracker.dir/build.make:62: recipe for target 'CMakeFiles/xbt_tracker.dir/home/user/Desktop/xbt-master/misc/bt_misc.cpp.o' failed
make[2]: *** [CMakeFiles/xbt_tracker.dir/home/user/Desktop/xbt-master/misc/bt_misc.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xbt_tracker.dir/all' failed
make[1]: *** [CMakeFiles/xbt_tracker.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by OlafvdSpek** [comment]
What does "with SOCK_NONBLOCK" mean?

**Comment by an0n666** [comment]
Meaning when I want to use non blocking sockets by defining -DSOCK_NONBLOCK in cmake

**Comment by OlafvdSpek** [comment]
XBT is always using non-blocking sockets..

**Comment by an0n666** [comment]
Oh. But then what’s the use of this
https://github.com/OlafvdSpek/xbt/blob/981c17d31fc9ad16448f83ded5854eaf95cb45b5/Tracker/tracker.cpp#L582

**Comment by OlafvdSpek** [comment]
It uses accept4 if it's available.
