### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by br00m** [OlafvdSpek/xbt#90]
/home/xbt/Tracker/tracker_input.cpp: In function ‘std::array<char, 16> to_ipv6(uint32_t)’:
/home/xbt/Tracker/tracker_input.cpp:6:68: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
    6 |  std::array<char, 16> res = { 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0 };
      |                                                                    ^
/home/xbt/Tracker/tracker_input.cpp:6:68: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ [-Wnarrowing]
CMakeFiles/xbt_tracker.dir/build.make:211: recipe for target 'CMakeFiles/xbt_tracker.dir/tracker_input.cpp.o' failed
make[2]: *** [CMakeFiles/xbt_tracker.dir/tracker_input.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/xbt_tracker.dir/all' failed
make[1]: *** [CMakeFiles/xbt_tracker.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

gcc (Debian 9.3.0-15) 9.3.0
latest version of xbt

**Comment by OlafvdSpek** [comment]
What platform?
Is char unsigned?

**Comment by br00m** [comment]
Hi Olaf,

platform is Arm. It seems this is the problem.
Normal platforms use a signed char however Arm uses unsigned char.
I changed tracker_input.cpp

static std::array<char, 16> to_ipv6(uint32_t v)
{
        std::array<char, 16> res = { 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0 };
        memcpy(&res[12], &v, 4);
        return res;
}
to
static std::array<signed char, 16> to_ipv6(uint32_t v)
{
        std::array<signed char, 16> res = { 0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0 };
        memcpy(&res[12], &v, 4);
        return res;
}

Now it is building.
Will test more this evening.

Grtz, Broom

**Comment by danfe** [comment]
The same bug had just been [fixed](https://cgit.freebsd.org/ports/commit/?id=735a7f11b1c53e58d7ab011b274724a84a8e5e15) in the FreeBSD port (more than two years after it was reported here).

**Comment by OlafvdSpek** [comment]
This unused function was removed in 28ababcc752f046c868c4a4563f79d3ffd36add5
