### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by rveyn** [OlafvdSpek/xbt#96]
~/xbt/Tracker# make
[  7%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/database.cpp.o
[ 15%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/sha1.cpp.o
[ 23%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/socket.cpp.o
[ 30%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/sql_query.cpp.o
[ 38%] Building CXX object CMakeFiles/xbt_tracker.dir/root/xbt/misc/xcc_z.cpp.o
[ 46%] Building CXX object CMakeFiles/xbt_tracker.dir/config.cpp.o
[ 53%] Building CXX object CMakeFiles/xbt_tracker.dir/connection.cpp.o
[ 61%] Building CXX object CMakeFiles/xbt_tracker.dir/epoll.cpp.o
[ 69%] Building CXX object CMakeFiles/xbt_tracker.dir/tracker.cpp.o
[ 76%] Building CXX object CMakeFiles/xbt_tracker.dir/tracker_input.cpp.o
[ 84%] Building CXX object CMakeFiles/xbt_tracker.dir/transaction.cpp.o
[ 92%] Linking CXX executable xbt_tracker
/usr/bin/ld: cannot find -lmysqlclient
/usr/bin/ld: cannot find -lsystemd
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xbt_tracker.dir/build.make:249: xbt_tracker] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/xbt_tracker.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

Debian 10, Mariadb

**Comment by VisiGod** [comment]
You're missing the libraries for mysqlclient and systemd.

You should make:
apt-get install cmake default-libmysqlclient-dev g++ git libboost-dev make zlib1g-dev

Before trying to compile xbt_tracker

**Comment by VisiGod** [comment]
Please try the following (my server is CentOS so maybe a little different on Debian):

# Link mysql library to /lib
ln -s /usr/lib64/mysql/libmysqlclient.so /usr/lib/libmysqlclient.so

# install systemd-devel
dnf install systemd-devel (could be apt-get install libsystemd-dev in Debian??)

#Link systemd library to /lib
ln -s /usr/lib64/libsystemd.so.0 /usr/lib/libsystemd.so.0
