### ISSUE TITLE
Issue using XBT through NGINX

### ISSUE THREAD

**Issue by bshuman** [OlafvdSpek/xbt#99]
This version of XBT doesn't appear to ingest the clients real IP via /GET URL parameter  ip= can you please provide a solution? 
I wouldn't mind if I had to disable IPv6 just to get a NGINX rev-proxy method working so I can secure the tracker. 

Thank you in advance for your time. 
[examples.txt](https://github.com/OlafvdSpek/xbt/files/6308714/examples.txt)

**Comment by darkalchemy** [comment]
This was addressed in #94

**Comment by bshuman** [comment]
That worked! Thank you.
